config/routes.rb
Eventsite::Application.routes.draw do
  resources :paymentaccounts


  resources :pins


  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_for :installs


  match '/pins/:action(/:pin_id)', :controller => 'pins'
  match '/paymentaccounts/:action(/:paymentaccount_id)', :controller => 'paymentaccounts'

  get 'about' => 'pages#about'

  get 'myevent' => 'pages#myevent'

  get 'newpaymentaccount' => 'paymentaccounts#new'


  root :to => 'pins#index'











end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :image_remote_url, :event_name, :price, :wepay_access_token, :wepay_account_id


  validates :event_name, presence: true
  validates :event_name, :length => { :in => 5..120}
  validates :description, presence: true
	validates :user_id, presence: true
  validates :price, presence: true

	
	has_attached_file :image, styles: { medium: "320x240" }
	validates_attachment :image, presence: true,
																content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
																size: { less_than: 5.megabytes }

  belongs_to :user
  
  def image_remote_url=(url_value)
  	self.image = URI.parse(url_value) unless url_value.blank?
  	super
  end


  # get the authorization url for this farmer. This url will let the farmer 
  # register or login to WePay to approve our app.

  # returns a url
  def wepay_authorization_url(redirect_uri)
    #Eventsite::Application::WEPAY.oauth2_authorize_url(redirect_uri, self.email, self.name)
    Eventsite::Application::WEPAY.oauth2_authorize_url(redirect_uri)
  end

  # takes a code returned by wepay oauth2 authorization and makes an api call to generate oauth2 token for this farmer.
  def request_wepay_access_token(code, redirect_uri)
    response = Eventsite::Application::WEPAY.oauth2_token(code, redirect_uri)
    if response['error']
      raise "Error - "+ response['error_description']
    elsif !response['access_token']
      raise "Error requesting access from WePay"
    else
      self.wepay_access_token = response['access_token']
      self.save
      #create WePay account
      self.create_wepay_account
    end
  end

  def has_wepay_access_token?
    !self.wepay_access_token.nil?
  end

  # makes an api call to WePay to check if current access token for farmer is still valid
  def has_valid_wepay_access_token?
    if self.wepay_access_token.nil?
      return false
    end
    response = Eventsite::Application::WEPAY.call("/user", self.wepay_access_token)
    response && response["user_id"] ? true : false
  end

  def has_wepay_account?
    self.wepay_account_id != 0 && !self.wepay_account_id.nil?
  end

  # creates a WePay account for this farmer with the farm's name
  def create_wepay_account
    if self.has_wepay_access_token? && !self.has_wepay_account?
      params = { :name => self.event_name, :description => "Tickets for " + self.event_name }     
      response = Eventsite::Application::WEPAY.call("/account/create", self.wepay_access_token, params)

      if response["account_id"]
        self.wepay_account_id = response["account_id"]
        return self.save
      else
        raise "Error - " + response["error_description"]
      end

    end   
    raise "Error - cannot create WePay account"
  end
  # creates a checkout object using WePay API for this farmer
  def create_checkout(redirect_uri)
    # calculate app_fee as 4% of produce price
    app_fee = self.price * 0.04
    #correct_pin = self.find(params[:id])
    correct_wepay_account_id = Paymentaccount.find_by_user_id(self.user_id).wepay_account_id
    correct_wepay_access_token = Paymentaccount.find_by_user_id(self.user_id).wepay_access_token

    params = { 
      :account_id => correct_wepay_account_id, 
      :short_description => "#{self.event_name} hosted by #{user.name}",
      :type => :GOODS,
      :amount => self.price,      
      :app_fee => app_fee,
      :fee_payer => :payee,     
      :mode => :iframe,
      :redirect_uri => redirect_uri
    }
    response = Eventsite::Application::WEPAY.call('/checkout/create', correct_wepay_access_token, params)

    if !response
      raise "Error - no response from WePay"
    elsif response['error']
      raise "Error - " + response["error_description"]
    end

    return response
  end

  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :oauth, :buy, :payment_success]



  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
      format.js
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])
    @is_admin = current_user && current_user.id == @pin.user_id
    @related_paymentaccount = Paymentaccount.find_by_user_id(@pin.user_id)



    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
  
  def pin_params
    params.require(:pin).permit(:event_name, :description, :image, :price)
  end

  # GET /farmers/oauth/1
  def oauth
    if !params[:code]
      return redirect_to('/')
    end

    redirect_uri = url_for(:controller => 'pins', :action => 'oauth', :pin_id => params[:pin_id], :host => request.host_with_port)
    @pin = Pin.find(params[:pin_id])
    begin
      @pin.request_wepay_access_token(params[:code], redirect_uri)
    rescue Exception => e
      error = e.message
    end

    if error
      redirect_to @pin, alert: error
    else
      redirect_to @pin, notice: 'We successfully connected you to WePay!'
    end
  end

  # GET /farmers/buy/1
  def buy
    redirect_uri = url_for(:controller => 'pins', :action => 'payment_success', :pin_id => params[:pin_id], :host => request.host_with_port)
    @pin = Pin.find(params[:pin_id])
    begin
      @checkout = @pin.create_checkout(redirect_uri)
    rescue Exception => e
      redirect_to @pin, alert: e.message
    end
  end

  # GET /farmers/payment_success/1
  def payment_success
    @pin = Pin.find(params[:pin_id])
    if !params[:checkout_id]
      return redirect_to @pin, alert: "Error - Checkout ID is expected"
    end
    if (params['error'] && params['error_description'])
      return redirect_to @pin, alert: "Error - #{params['error_description']}"
    end
    redirect_to @pin, notice: "Thanks for the payment! You should receive a confirmation email shortly."
  end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <%= f.input :image, label: "Upload an image" %>
  <%= f.input :image_remote_url, label: "Or enter a URL" %>
  <%= f.input :event_name, as: :text, input_html: { rows: "1" } %>
  <%= f.input :description, as: :text, input_html: { rows: "3" } %>
  <%= f.input :price, label: "Price" %>


  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
	<%= link_to (image_tag pin.image(:medium)), pin %>
	<p></p>
	<p class="event_name">
		<b>
			<%= pin.event_name %>
		</b>
	</p>
	<p class="description">
		<%= pin.description %>
	</p>
	<p>
		<strong>
			Posted by <%= pin.user.name %>
		</strong>
	</p>
	<% if current_user == pin.user %>
		<p>
			<%= link_to 'Edit', edit_pin_path(pin) %>
			<%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
		</p>
	<% end %>
</div>

app/views/pins/buy.html.erb
<h1>Buy e-Tickets for <%= @pin.event_name %> for <%= number_to_currency(@pin.price, :unit => "$") %></h1>
<p><%= link_to "← back to " + @pin.event_name, @pin =%></p>

<div id="wepay-iframe-div">
	<script type="text/javascript" src="https://www.wepay.com/js/iframe.wepay.js">
	</script>

	<script type="text/javascript">
		WePay.iframe_checkout("wepay-iframe-div", "<%= @checkout['checkout_uri'] %>");
	</script>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<div id="pins">
  <%= render @pins %>
</div>

<%= will_paginate @pins %>

app/views/pins/index.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
    $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
    $('.pagination').remove();
<% end %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @pin.image %>
			<p></p>
			<h2>
			  <%= @pin.event_name %>
			</h2>	
			<p>
			  Description: <%= @pin.description %>
			</p>
			<p>
				<b>Admission Fee:</b> $<%= @pin.price %>
			<p>
			  <b>Hosted by</b> <%= @pin.user.name %>
			</p>

			<% if (@related_paymentaccount.has_wepay_account? && !@is_admin) %>
				<%= link_to "Buy e-tickets for this event now!", "/pins/buy/#{@pin.id}", :class => 'btn btn-danger btn-large', :id => 'buy-now-button' %>
			<% end %>

			<% if false %> 
			this is a comment out block
			<% if (@pin.has_wepay_account? && !@is_admin) %>
				<%= link_to "Buy e-tickets for this event now!", "/pins/buy/#{@pin.id}", :class => 'btn btn-danger btn-large', :id => 'buy-now-button' %>
			<% end %>

			<% if (@is_admin && (!@pin.has_valid_wepay_access_token? || !@pin.has_wepay_account?)) %>
			  <p>
			    <b>Please sign into WePay to allow you to receive payments for this event: </b>
				<% redirect_uri = url_for(:controller => 'pins', :action => 'oauth', :pin_id => @pin.id, :host => request.host_with_port) %>
			    <a class="btn btn-primary" href="<%= @pin.wepay_authorization_url(redirect_uri) %>">Click here to sign in or create a new WePay account</a>
			  </p>
			<% end %>
			end comment block
			<% end %>

			</br>

			<% if current_user == @pin.user %>
				<%= link_to 'Edit', edit_pin_path(@pin) %> |
			<% end %>
			<%= link_to 'Back', pins_path %>
		</div>
	</div>
</div>

