config/routes.rb
Eventsite::Application.routes.draw do
  resources :paymentaccounts


  resources :pins


  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_for :installs


  match '/pins/:action(/:pin_id)', :controller => 'pins'
  match '/paymentaccounts/:action(/:paymentaccount_id)', :controller => 'paymentaccounts'

  get 'about' => 'pages#about'

  get 'myevent' => 'pages#myevent'

  get 'newpaymentaccount' => 'paymentaccounts#new'


  root :to => 'pins#index'











end

app/models/paymentaccount.rb
class Paymentaccount < ActiveRecord::Base
  attr_accessible :agreement, :wepay_access_token, :wepay_account_id

  validates :user_id, presence: true

  belongs_to :user


	# get the authorization url for this farmer. This url will let the farmer 
	# register or login to WePay to approve our app.

	# returns a url
	def wepay_authorization_url(redirect_uri)
	  Eventsite::Application::WEPAY.oauth2_authorize_url(redirect_uri)
	end

	# takes a code returned by wepay oauth2 authorization and makes an api call to generate oauth2 token for this farmer.
	def request_wepay_access_token(code, redirect_uri)
	  response = Eventsite::Application::WEPAY.oauth2_token(code, redirect_uri)
	  if response['error']
	    raise "Error - "+ response['error_description']
	  elsif !response['access_token']
	    raise "Error requesting access from WePay"
	  else
	    self.wepay_access_token = response['access_token']
	    self.save
			#create WePay account
	    self.create_wepay_account
	  end
	end

	def has_wepay_access_token?
	  !self.wepay_access_token.nil?
	end

	# makes an api call to WePay to check if current access token for farmer is still valid
	def has_valid_wepay_access_token?
	  if self.wepay_access_token.nil?
	    return false
	  end
	  response = Eventsite::Application::WEPAY.call("/user", self.wepay_access_token)
	  response && response["user_id"] ? true : false
	end

	def has_wepay_account?
	  self.wepay_account_id != 0 && !self.wepay_account_id.nil?
	end

	# creates a WePay account for this farmer with the farm's name
	def create_wepay_account
	  if self.has_wepay_access_token? && !self.has_wepay_account?
	    params = { :name => user.name, :description => "Connect Wepay account to Eventsite " }			
	    response = Eventsite::Application::WEPAY.call("/account/create", self.wepay_access_token, params)

	    if response["account_id"]
	      self.wepay_account_id = response["account_id"]
	      return self.save
	    else
	      raise "Error - " + response["error_description"]
	    end

	  end		
	  raise "Error - cannot create WePay account"
	end
end

app/controllers/paymentaccounts_controller.rb
class PaymentaccountsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :oauth]
  # GET /paymentaccounts
  # GET /paymentaccounts.json
  def index
    @paymentaccounts = Paymentaccount.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @paymentaccounts }
    end
  end

  # GET /paymentaccounts/1
  # GET /paymentaccounts/1.json
  def show
    @paymentaccount = Paymentaccount.find(params[:id])
    @is_admin = current_user && current_user.id == @paymentaccount.user_id

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @paymentaccount }
    end
  end

  # GET /paymentaccounts/new
  # GET /paymentaccounts/new.json
  def new
    @paymentaccount = current_user.paymentaccounts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @paymentaccount }
    end
  end

  # GET /paymentaccounts/1/edit
  def edit
    @paymentaccount = current_user.paymentaccounts.find(params[:id])
  end

  # POST /paymentaccounts
  # POST /paymentaccounts.json
  def create
    @paymentaccount = current_user.paymentaccounts.new(params[:paymentaccount])

    respond_to do |format|
      if @paymentaccount.save
        format.html { redirect_to @paymentaccount } #notice: 'Paymentaccount was successfully created.' }
        format.json { render json: @paymentaccount, status: :created, location: @paymentaccount }
      else
        format.html { render action: "new" }
        format.json { render json: @paymentaccount.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /paymentaccounts/1
  # PUT /paymentaccounts/1.json
  def update
    @paymentaccount = current_user.paymentaccounts.find(params[:id])

    respond_to do |format|
      if @paymentaccount.update_attributes(params[:paymentaccount])
        format.html { redirect_to @paymentaccount, notice: 'Paymentaccount was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @paymentaccount.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paymentaccounts/1
  # DELETE /paymentaccounts/1.json
  def destroy
    @paymentaccount = current_user.paymentaccounts.find(params[:id])
    @paymentaccount.destroy

    respond_to do |format|
      format.html { redirect_to paymentaccounts_url }
      format.json { head :no_content }
    end
  end
  
  def pin_params
    params.require(:paymentaccount).permit(:agreement)
  end

  # GET /farmers/oauth/1
  def oauth
    if !params[:code]
      return redirect_to('/')
    end

    redirect_uri = url_for(:controller => 'paymentaccounts', :action => 'oauth', :paymentaccount_id => params[:paymentaccount_id], :host => request.host_with_port)
    @paymentaccount = Paymentaccount.find(params[:paymentaccount_id])
    begin
      @paymentaccount.request_wepay_access_token(params[:code], redirect_uri)
    rescue Exception => e
      error = e.message
    end

    if error
      redirect_to @paymentaccount, alert: error
    else
      redirect_to @paymentaccount, notice: 'We successfully connected you to WePay!'
    end
  end
end

app/helpers/paymentaccounts_helper.rb
module PaymentaccountsHelper
end

app/views/paymentaccounts/_form.html.erb
<h2>Agreements</h2>
</br>
<p>Eventsite has partnered up with WePay in order to allow you to accept payments from your guests. All transactions are facilitated through WePay. You must check to agree that you will allow WePay to handle your payment information.</p>
</br>

<%= simple_form_for(@paymentaccount) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :agreement, label: "Check to agree" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/paymentaccounts/edit.html.erb
<h1>Editing paymentaccount</h1>

<%= render 'form' %>

<%= link_to 'Show', @paymentaccount %> |
<%= link_to 'Back', paymentaccounts_path %>

app/views/paymentaccounts/index.html.erb
<h1>Listing paymentaccounts</h1>

<table>
  <tr>
    <th>User</th>
    <th>Agreement</th>
    <th>Wepay access token</th>
    <th>Wepay account</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @paymentaccounts.each do |paymentaccount| %>
  <tr>
    <td><%= paymentaccount.user_id %></td>
    <td><%= paymentaccount.agreement %></td>
    <td><%= paymentaccount.wepay_access_token %></td>
    <td><%= paymentaccount.wepay_account_id %></td>
    <td><%= link_to 'Show', paymentaccount %></td>
    <td><%= link_to 'Edit', edit_paymentaccount_path(paymentaccount) %></td>
    <td><%= link_to 'Destroy', paymentaccount, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Paymentaccount', new_paymentaccount_path %>

app/views/paymentaccounts/new.html.erb
<h1>New paymentaccount</h1>


<%= render 'form' %>



<%= link_to 'Back', paymentaccounts_path %>

app/views/paymentaccounts/show.html.erb
<% if false %>
<p id="notice"><%= notice %></p>
<% end %>

<p>
  <b>User:</b>
  <%= @paymentaccount.user_id %>
</p>

<% if (@is_admin && (!@paymentaccount.has_valid_wepay_access_token? || !@paymentaccount.has_wepay_account?)) %>
  <p>
    <b>Please create an account with Wepay to manage your money: </b>
  </p>
	<% redirect_uri = url_for(:controller => 'paymentaccounts', :action => 'oauth', :paymentaccount_id => @paymentaccount.id, :host => request.host_with_port) %>
    <a class="btn btn-primary" href="<%= @paymentaccount.wepay_authorization_url(redirect_uri) %>">Click here to create your Wepay account</a>
<% end %>

</br>
</br>


<%= link_to 'Edit', edit_paymentaccount_path(@paymentaccount) %> |
<%= link_to 'Back', paymentaccounts_path %>